"""Phase 2 Schema Enhancements

Revision ID: 173aa4ca4182
Revises: 5d0c08e2d628
Create Date: 2026-02-14 01:43:00.376651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '173aa4ca4182'
down_revision: Union[str, None] = '5d0c08e2d628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_room_members_role'), 'room_members', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_members_role'), table_name='room_members')
    # ### end Alembic commands ###
